#The message that we want sent to the player when they try to write and illegal book
message: "&cВы используете Unicode символы!"
PreventBowBombExploit: true # Please report any problems in GitHub/Discord.
MaxBowSquaredVelocity: 15 # Fully pulled bow is ~9-10. 15 is default just to be safe.
PreventBurrow: true # Preliminary burrow patch, please test. Makes players take damage every time they move when their feet are in a block
BurrowDamageWhenMoving: 1 # Half a heart of damage every time you move.
TeleportBurrow: false #Teleport player above block
PreventBurrowIfBlockAbove: false # Prevent burrow even if there is a block above the block they are burrowing in, please note this may allow creating an "elevator", players will keep teleporting up until they hit air
# Patch future/rusher packet fly
PreventPacketFly: true
# Max teleport packets per 10 seconds, this is how the packet fly works, 25 is usually fine, if you go lower players may get stuck.
MaxTeleportPacketsPer10Seconds: 25
LogPacketFlyEvents: true
# Patches the future/rusherhack/kamiblue 2b2t elytra fly exploit
PatchPacketElytraFly: true
# Recommended to not go lower as there could be false positives.
MaxElytraOpensPer10Seconds: 25 # Will only allow players to go about 85km/h on kami blue, and won't even
# Patch futureclient/rusherhack boat fly exploit
# This does not affect boats at all! Even on land.
BoatflyPatch: true
MaxEntityPacketsPer10Seconds: 15 # Only counts for boats
LogBoatFlyEvents: true
PreventCraftingRecipeLagExploit: true
CraftingRecipeDelay: 5 # in ticks
CrystalDelay: 10

